### ISSUE TITLE
Do I must select centralus?

### ISSUE THREAD

**Issue by xiaobingb001** [DataJuggler/Simon#1]
Simon version is 1.0.4
I have set the environment variables for Speechkey and SpeechRegion.
when I check Speak button, I get the message:
You must set the environment variables for Speechkey and SpeechRegion must be 'centralus'.
I select the region is eastasia.
Do I must select centralus?
Thanks.

**Comment by DataJuggler** [comment]
You might try centralus and see if it works. I have never tested anything else.I just woke up. Let me walk my dog and I will look at this.Corby
      
        
        
          On Oct 21 2023, at 9:35 pm, xiaobingb001 ***@***.***> wrote:
          
        
        
          
Simon version is 1.0.4
I have set the environment variables for Speechkey and SpeechRegion.
when I check Speak button, I get the message:
You must set the environment variables for Speechkey and SpeechRegion must be 'centralus'.
I select the region is eastasia.
Do I must select centralus?
Thanks.

**Comment by DataJuggler** [comment]
I just checked the code. I had the messages in the wrong place. I am going to make a new version and will publish it soon, but for now it looks like your Output Folder probably does not exist.Try selecting an output folder, or make sure c:\Temp exists if you are using the default directory. Let me know if that works.I will update the new version and the instructions soon.Sorry, this is a new project, and I haven't done a lot of testing yet.Corby
      
        
        
          On Oct 22 2023, at 6:46 am, ***@***.*** wrote:
          
        
        
          You might try centralus and see if it works. I have never tested anything else.I just woke up. Let me walk my dog and I will look at this.Corby
      
        
        
          On Oct 21 2023, at 9:35 pm, xiaobingb001 ***@***.***> wrote:
          
        
        
          
Simon version is 1.0.4
I have set the environment variables for Speechkey and SpeechRegion.
when I check Speak button, I get the message:
You must set the environment variables for Speechkey and SpeechRegion must be 'centralus'.
I select the region is eastasia.
Do I must select centralus?
Thanks.

**Comment by DataJuggler** [comment]
Hi, I just published a new release. The new release has better validation messages.You must uninstall the old version and then install the new one for now (I am working on Upgrades next).Let me know if it still doesn't work for you.Thanks for trying out Simon, and sorry you are having problems.Corby
      
        
        
          On Oct 22 2023, at 7:23 am, ***@***.*** wrote:
          
        
        
          I just checked the code. I had the messages in the wrong place. I am going to make a new version and will publish it soon, but for now it looks like your Output Folder probably does not exist.Try selecting an output folder, or make sure c:\Temp exists if you are using the default directory. Let me know if that works.I will update the new version and the instructions soon.Sorry, this is a new project, and I haven't done a lot of testing yet.Corby
      
        
        
          On Oct 22 2023, at 6:46 am, ***@***.*** wrote:
          
        
        
          You might try centralus and see if it works. I have never tested anything else.I just woke up. Let me walk my dog and I will look at this.Corby
      
        
        
          On Oct 21 2023, at 9:35 pm, xiaobingb001 ***@***.***> wrote:
          
        
        
          
Simon version is 1.0.4
I have set the environment variables for Speechkey and SpeechRegion.
when I check Speak button, I get the message:
You must set the environment variables for Speechkey and SpeechRegion must be 'centralus'.
I select the region is eastasia.
Do I must select centralus?
Thanks.

**Comment by xiaobingb001** [comment]
I have download the new version and  set output folder. It works.
thank you so much for all ur help

**Comment by DataJuggler** [comment]
Thank you for helping me test it.Corby
      
        
        
          On Oct 23 2023, at 2:22 am, xiaobingb001 ***@***.***> wrote:
          
        
        
          
I have download the new version and  set output folder. It works.
thank you so much for all ur help
